### ISSUE TITLE
可运行exe在哪里？没看到。微信nlanguage

### ISSUE THREAD

**Issue by nissansz** [liulei901112/TextLocator#1]
可运行exe在哪里？没看到。微信nlanguage

**Comment by liulei901112** [comment]
发布的exe在gitee上，github只是同步了代码。发自我的手机-------- 原始邮件 --------发件人： nissansz ***@***.***>日期： 2022年7月22日周五 11:41收件人： liulei901112/TextLocator ***@***.***>抄送： Subscribed ***@***.***>主    题： [liulei901112/TextLocator] 可运行exe在哪里？没看到。微信nlanguage (Issue #1)

可运行exe在哪里？没看到。微信nlanguage

**Comment by nissansz** [comment]
好的，在gitee提问了

你好，有几个问题？帮忙看看怎么解决。
1. 搜索，类似以下这些词，没有结果。被列入为禁用词了？怎么取消禁用？
我们，他们，你们，我，....

2.第一次启动时界面没法最大化？拉动最右面的窗口到右边，然后才能看到按钮
后面再次启动可以看到按钮

3. 怎么起用正则查询？

4.我尝试用一句英文进行搜索，结果是按or查询出所有结果，怎么只显示含有整句话的文档？


5. 文件内容预览窗，换行符消失了，能添加一下吗？
![输入图片说明](https://images.gitee.com/uploads/images/2022/0722/115854_0875315f_492319.png "屏幕截图.png")

**Comment by liulei901112** [comment]
我已经看到并回复您了，相关问题已记录。发自我的手机-------- 原始邮件 --------发件人： nissansz ***@***.***>日期： 2022年7月23日周六 17:56收件人： liulei901112/TextLocator ***@***.***>抄送： 卖萌小老头 ***@***.***>, Comment ***@***.***>主    题： Re: [liulei901112/TextLocator] 可运行exe在哪里？没看到。微信nlanguage (Issue #1)
好的，在gitee提问了
你好，有几个问题？帮忙看看怎么解决。
搜索，类似以下这些词，没有结果。被列入为禁用词了？怎么取消禁用？
我们，他们，你们，我，....
2.第一次启动时界面没法最大化？拉动最右面的窗口到右边，然后才能看到按钮
后面再次启动可以看到按钮
怎么起用正则查询？
4.我尝试用一句英文进行搜索，结果是按or查询出所有结果，怎么只显示含有整句话的文档？
文件内容预览窗，换行符消失了，能添加一下吗？

**Comment by nissansz** [comment]
好的，看gitee
