### ISSUE TITLE
C: 无法作为搜索区

### ISSUE THREAD

**Issue by boxstudy** [liulei901112/TextLocator#2]

**Comment by liulei901112** [comment]
![C盘](http://cdn.bitsport.com.cn/images/202212011045910.png)
当前仓库最新代码，我这边测试时没问题的。如果可以的话，麻烦把logs目录打包发我邮箱（liulei901112@163.com），我检查下是不是哪里有问题。谢谢！

**Comment by liulei901112** [comment]
我这边还发现了个问题，代码支持js。但是如果选定的目录有node_modules，那这个过程会很长。下个版本增加过滤条件把一些原生sdk包和扩展目录依赖包去掉。

**Comment by liulei901112** [comment]
已经增加了相关过滤规则，并优化了代码。麻烦确认是否正常，谢谢！
