### ISSUE TITLE
关于.m文件的索引

### ISSUE THREAD

**Issue by ForeUP** [liulei901112/TextLocator#3]
作者大大，不知道是否是我没找到设置的位置，目前来看除了列出类型的文件，其他类型的文本都无法索引啊，比如常用的matlab文件就没法查询了，可以参考下anytxt可以手动新建索引的文件类型

**Comment by liulei901112** [comment]
你好！很抱歉现在才回复消息。回老家了，github访问不稳定，所以就一直没回复你。
现在可用的文件类型和后缀都是代码内写的，文件内容解析需要不同的方式，所以不支持自定义文件类型或后缀的文件。不过这个可以考虑加入后期的改进中，谢谢你的参考建议。
